[package]
name = "drmtest"
version = "0.1.0"
authors = ["Felix Bernhardt <felix.bernhardt@mailbox.org>"]

[dependencies]
libc = "0.2"
memmap = "0.6.2"

[dependencies.sdl2]
version = "0.31"
features = ["bundled"]

